### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yuki51b** [yuki51b/scammer-s-notebook#27]
### 概要
issueを作成しましたので提出をします
[projectはこちらです](https://github.com/users/yuki51b/projects/1)

### 実装予定の機能
- [ ] AIによる詐欺診断機能
- [ ] 詐欺の詳細機能（詐欺師視点）
- [ ] 投稿機能
- [ ] ログイン機能
- [ ] ユーザー登録機能
- [ ] 管理者による詐欺情報管理機能
### 必要なページ
- [ ] トップページ
- [ ] 状況の入力ページ
- [ ] 診断結果表示ページ
- [ ] 詐欺情報詳細ページ
- [ ] 詐欺一覧ページ
- [ ] ログインページ
- [ ] ユーザー登録ページ
- [ ] 投稿一覧ページ
- [ ] 投稿作成ページ
- [ ] 詐欺一覧ページ（管理者用）
- [ ] 詐欺情報編集ページ（管理者用）
- [ ] 投稿詳細ページ
- [ ] お問い合わせページ
- [ ] プライバシーポリシーページ
- [ ] 利用規約ページ

**Comment by ky0613** [comment]
提出ありがとうございます。
気になった点をいくつかコメントします。

----

- ストーリーポイントが5や8のものは出来るだけ細分化してストーリーポイントが小さくなるようにした方が良いかと思います。
- レスポンシブ対応は後のissue全てで対応しないといけないので、実装方法の調査までにとどめても良いと思います。

**Comment by yuki51b** [comment]
ご指摘ありがとうございます！
issueを修正しましたので再提出します。
### 修正したこと
- [ ] 検索機能のissueが抜けていたので追加しました
- [ ] ストーリーポイントが、5と8　だったissueを細分化して3に変更しました
- [ ] レスポンシブ対応のissueの内容を実装方法の調査までに変更しました

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
MVPリリースに向けてがんばってください。
