### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by yuki51b** [yuki51b/scammer-s-notebook#88]
## MVPリリースのレビュー依頼を提出します。
MVPリリースまでの機能を実装しましたので、お忙しい中恐れ入りますがご確認のほどよろしくお願いします。

## 各種情報
サービス名: 詐欺師の手帳
サービスURL　: https://scammer-s-notebook.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] AIによる詐欺診断機能
- [x] 詐欺の詳細機能（詐欺師視点）
- [x] 投稿機能
- [x] ログイン機能
- [x] ユーザー登録機能
- [ ] 管理者による詐欺情報管理機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
なければこの項目は省略してください
### - 作らなくなった機能
- [x] 管理者による詐欺情報管理機能

### - 追加した機能 
- [x] 検索機能
- [x] オートコンプリート機能
- [x] ステップ式フォームの実装
- [x]  フラッシュメッセージの実装
- [x] 診断機能で「その他」を押した時に、textフィールドが飛び出す実装 

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

- [x] TOPページです。「マドフくん」はキャラクターの名前です。（変えるかも）
世界観として「天才詐欺師マドフくん」の「手帳」を使って「詐欺の診断」や詐欺について学ぼうというコンセプトです。
[![Image from Gyazo](https://i.gyazo.com/4493fc7229b57357407501cbd356e32b.png)](https://gyazo.com/4493fc7229b57357407501cbd356e32b)

- [x] ステップ式フォームの実装（step1)の画像です。
[![Image from Gyazo](https://i.gyazo.com/6e76041e7a86b6ededac84b72321106d.png)](https://gyazo.com/6e76041e7a86b6ededac84b72321106d)

- [x] ７つの質問に回答すると、どんな詐欺の可能性があるか、その詐欺について一言の説明、詐欺のポイントを３つ表示してくれます
[![Image from Gyazo](https://i.gyazo.com/b68201b31684e00337686e7ff27dfd86.png)](https://gyazo.com/b68201b31684e00337686e7ff27dfd86)

- [x] 詐欺の詳細＝詐欺師視点での記載になっています
[![Image from Gyazo](https://i.gyazo.com/d157fbef4f67eb68adfc377a3c2bada7.png)](https://gyazo.com/d157fbef4f67eb68adfc377a3c2bada7)

- [x] 診断機能で「その他」を押した時に、textフィールドが飛び出す実装 
[![Image from Gyazo](https://i.gyazo.com/b89bd2cc79c6d8d4d10480fa2b86171d.gif)](https://gyazo.com/b89bd2cc79c6d8d4d10480fa2b86171d)

- [x] 投稿一覧、詐欺一覧それぞれで詐欺名で検索ができます。オートコンプリートも実装しています（デザイン未対応)
[![Image from Gyazo](https://i.gyazo.com/3477f78db54b9b5a3b744b4b80ff9430.gif)](https://gyazo.com/3477f78db54b9b5a3b744b4b80ff9430)

**Comment by tarakish** [comment]
投稿一覧で検索ワードと一致する投稿が存在しない場合、すべての投稿が表示されるようでした。
上記の挙動が意図しているものかどうか一度ご確認をお願いします。

**Comment by yuki51b** [comment]
意図している挙動ではないです。修正に努めます。　ご指摘ありがとうございます！

**Comment by yuki51b** [comment]
投稿一覧で検索ワードと一致する投稿が存在しない場合、すべての投稿が表示される挙動を投稿が表示されないようにする挙動に修正しました。

お忙しい中、恐れ入りますがご確認のほど、よろしくお願いします。
[![Image from Gyazo](https://i.gyazo.com/e5adb6ad2d365ba84278e1c62e1c2b93.gif)](https://gyazo.com/e5adb6ad2d365ba84278e1c62e1c2b93)

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
上記、アプリのURLにてアクセスできませんでした。
大変申し訳ないのですが、ご確認いただいてもよろしいでしょうか？

**Comment by yuki51b** [comment]
## MVPアプリを再提出します
ご返信ありがとうございます。
一旦、自分での確認と他の同期の方に同じURLで確認していただいたのですが、問題なくアクセスはできておりまして、
ちょっと今回の原因がわかりませんでした。
デプロイ先のrenderがスリープ状態が故にアクセスに時間がかかったのかと考え、下記記事を参考に監視するようにしましたので、お手数をおかけして申し訳ありませんがご確認のほどよろしくお願いします。
参考記事　https://qiita.com/ppputtyo/items/2ab44303dcfabeb7b23e

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
ご対応いただきありがとうございます。
アクセスに時間がかかっていて入れなかったため、上記対応で良いと思います。

アクセスできました！

機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
